DECLARE 
---
--- TYPE FOR REF CURSOR 
TYPE  CUR_TYPE  IS REF CURSOR;
--
----
C1  CUR_TYPE;

BEGIN  

 OPEN C1 FOR  SELECT  'QUERY_ONE' FROM DUAL;
 ---IF CONDITION FOR CHECK CURSOR IS OPEN OR NOT 
 IF  C1%ISOPEN THEN
     DBMS_OUTPUT.PUT_LINE('THE CURSOR IS OPEN.');
 END IF;
---CLOSE CURSOR 
CLOSE C1;

 --NOW I CHANGE MY CURSOR QUERY 
 --
 --
 IF NOT C1%ISOPEN THEN
 DBMS_OUTPUT.PUT_LINE('THE CURSOR IS CLOSED.');
      --
      -- OPEN C1 FOR ANOTHER QUERY                     
     OPEN C1 FOR  SELECT  'QUERY_TWO' FROM DUAL;
     DBMS_OUTPUT.PUT_LINE('THE CURSOR IS OPEN.');
     CLOSE C1;
     ---
 END IF;

END;
/
