select *
from PER_ABSENCE_ATTENDANCE_TYPES s;



 SELECT PPT.USER_PERSON_TYPE,PAA.EMPLOYMENT_CATEGORY,hla.LOCATION_CODE
     
      FROM PER_PERSON_TYPE_USAGES_F PTYPE,
           PER_PERSON_TYPES         PPT,
           PER_ALL_PEOPLE_F         PAPF,
           apps.hr_locations_all hla,
           apps.per_all_assignments_f PAA
           
     WHERE PTYPE.PERSON_ID = PAPF.PERSON_ID
       AND PPT.PERSON_TYPE_ID = PTYPE.PERSON_TYPE_ID
       AND SYSDATE BETWEEN PTYPE.EFFECTIVE_START_DATE AND
           PTYPE.EFFECTIVE_END_DATE
       AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND
           PAPF.EFFECTIVE_END_DATE
       AND SYSDATE BETWEEN PAA.EFFECTIVE_START_DATE AND
           PAA.EFFECTIVE_END_DATE
       AND PAA.PERSON_ID=PAPF.PERSON_ID
       AND hla.location_id(+) = paa.location_id
       AND PAPF.EMPLOYEE_NUMBER = 1001;
       
